# config/travis/solr_wrapper_test.yml
version: 7.1.0
port: 8985
instance_dir: solr-test
download_dir: dep_cache
mirror_url: http://lib-solr-mirror.princeton.edu/dist/
collection:
  persist: false
  dir: solr/config
  name: cho-test
