inherit_gem:
  niftany: niftany_rubocop.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/**/*'

RSpec/ContextWording:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/deploy.rb'
    - 'app/views/data_dictionary/fields/_dictionary_field.json.jbuilder'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
