require: rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/psu-stewardship/guides/master/style/ruby/.rubocop.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4.1

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'
