development:
  host: dirapps.aset.psu.edu
  port: 389
  base: dc=psu,dc=edu
  group_base: dc=psu,dc=edu
test:
  host: dirapps.aset.psu.edu
  port: 389
  base: dc=psu,dc=edu
  group_base: dc=psu,dc=edu
integration:
  host: dirapps.aset.psu.edu
  port: 389
  base: dc=psu,dc=edu
  group_base: dc=psu,dc=edu
  uid: uid
production:
  host: dirapps.aset.psu.edu
  port: 389
  base: dc=psu,dc=edu
  group_base: dc=psu,dc=edu
  uid: uid
